# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "pdr-api"

[default.build.parameters]
cached = false
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "pdr-api"
region = "ca-central-1"
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[lza-test]
[lza-test.global.parameters]
stack_name = "pdr-api-lza-test"

[lza-test.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "pdr-api"
region = "ca-central-1"
image_repositories = []
parameter_overrides = [
  "Env=lza-test",
  "OpenSearchSecondaryDomainName=pdr-opensearch",
  "TableNameRegister=NameRegister-lza-test",
  "TableNameAudit=Audit-lza-test"
]

[lza-dev]
[lza-dev.global.parameters]
stack_name = "pdr-api-lza-dev"

[lza-dev.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "pdr-api"
region = "ca-central-1"
image_repositories = []
parameter_overrides = [
  "Env=lza-dev",
  "OpenSearchSecondaryDomainName=pdr-opensearch",
  "TableNameRegister=NameRegister-lza-dev",
  "TableNameAudit=Audit-lza-dev"
]
