# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "pdr-admin"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "pdr-admin"
region = "ca-central-1"
image_repositories = []
parameter_overrides=[
  "ProjectName=pdr-admin",
  "DistOriginPath=latest",
  "ApiGatewayId=zloys5cfvf",
  "Env=dev",
  "AWSRegion=ca-central-1",
  "ApiStage=api"
]

[dev]
[dev.global.parameters]
stack_name = "pdr-admin"

[dev.build.parameters]
cached = true
parallel = true

[dev.validate.parameters]
lint = true

[dev.package.parameters]
resolve_s3 = true

[dev.sync.parameters]
watch = true

[dev.local_start_api.parameters]
warm_containers = "EAGER"

[dev.local_start_lambda.parameters]
warm_containers = "EAGER"

[dev.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "pdr-admin"
region = "ca-central-1"
image_repositories = []
parameter_overrides=[
  "ProjectName=pdr-admin",
  "DistOriginPath=latest",
  "ApiGatewayId=zloys5cfvf",
  "Env=dev",
  "AWSRegion=ca-central-1",
  "ApiStage=api"
]

[test]
[test.global.parameters]
stack_name = "pdr-admin"

[test.build.parameters]
cached = true
parallel = true

[test.validate.parameters]
lint = true

[test.package.parameters]
resolve_s3 = true

[test.sync.parameters]
watch = true

[test.local_start_api.parameters]
warm_containers = "EAGER"

[test.local_start_lambda.parameters]
warm_containers = "EAGER"

[test.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "pdr-admin"
region = "ca-central-1"
image_repositories = []
parameter_overrides=[
  "ProjectName=pdr-admin",
  "DistOriginPath=latest",
  "ApiGatewayId=18dgy3grjj",
  "Env=test",
  "AWSRegion=ca-central-1",
  "ApiStage=api"
]

[prod]
[prod.global.parameters]
stack_name = "pdr-admin"

[prod.build.parameters]
cached = true
parallel = true

[prod.validate.parameters]
lint = true

[prod.package.parameters]
resolve_s3 = true

[prod.sync.parameters]
watch = true

[prod.local_start_api.parameters]
warm_containers = "EAGER"

[prod.local_start_lambda.parameters]
warm_containers = "EAGER"

[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "pdr-admin"
region = "ca-central-1"
image_repositories = []
parameter_overrides=[
  "ProjectName=pdr-admin",
  "DistOriginPath=latest",
  "ApiGatewayId=9g4piu88n8",
  "Env=prod",
  "AWSRegion=ca-central-1",
  "ApiStage=api"
]

[lza-test]
[lza-test.global.parameters]
stack_name = "pdr-admin-lza-test"

[lza-test.build.parameters]
cached = true
parallel = true

[lza-test.validate.parameters]
lint = true

[lza-test.package.parameters]
resolve_s3 = true

[lza-test.sync.parameters]
watch = true

[lza-test.local_start_api.parameters]
warm_containers = "EAGER"

[lza-test.local_start_lambda.parameters]
warm_containers = "EAGER"

[lza-test.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "pdr-admin-lza-test"
region = "ca-central-1"
image_repositories = []
parameter_overrides=[
  "ProjectName=pdr-admin-lza-test",
  "DistOriginPath=latest",
  "ApiGatewayId=e8qk6n9teg",
  "Env=lza-test",
  "AWSRegion=ca-central-1",
  "ApiStage=api"
]

[lza-dev]
[lza-dev.global.parameters]
stack_name = "pdr-admin-lza-dev"

[lza-dev.build.parameters]
cached = true
parallel = true

[lza-dev.validate.parameters]
lint = true

[lza-dev.package.parameters]
resolve_s3 = true

[lza-dev.sync.parameters]
watch = true

[lza-dev.local_start_api.parameters]
warm_containers = "EAGER"

[lza-dev.local_start_lambda.parameters]
warm_containers = "EAGER"

[lza-dev.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "pdr-admin-lza-dev"
region = "ca-central-1"
image_repositories = []
parameter_overrides=[
  "ProjectName=pdr-admin-lza-dev",
  "DistOriginPath=latest",
  "ApiGatewayId=gw4ohkljkk",
  "Env=lza-dev",
  "AWSRegion=ca-central-1",
  "ApiStage=api"
]
