name: Deploy PDR-API Dev

run-name: Deploying ${{ github.ref_name }} (API) to dev

on:
  push:
    branches: [main]
    paths: "pdr-api/**"
  workflow_dispatch:

env:
  AWS_REGION: "${{ vars.PDR_API_AWS_REGION }}"
  DIRECTORY: "${{ vars.PDR_API_DIRECTORY }}"

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: "./$DIRECTORY"

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      ### Checkout GitHub Repo
      - name: Checkout repo
        uses:
          actions/checkout@v3

      ### Install if no cache exists
      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: |
           ${{ vars.PDR_API_DIRECTORY }}/${{ vars.PDR_API_DEPENDENCIES_PATH }}/yarn.lock
          cache: "yarn"
      - run: |
          cd ${{ vars.PDR_API_DEPENDENCIES_PATH }}
          yarn install --silent --frozen-lockfile

      ### Setup AWS SAM
      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      ### Assume AWS IAM Role
      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      ### Build inside Docker containers
      - name: SAM build
        run: |
          sam build --use-container
      ### Prevent prompts and failure when the stack is unchanged
      - name: SAM deploy
        env:
          STACK_NAME: ${{ vars.PDR_API_STACK_NAME }}
        run: |
          sam deploy --stack-name $STACK_NAME --no-confirm-changeset --no-fail-on-empty-changeset
