name: Deploy PDR-API Test

run-name: Deploying ${{ github.ref_name }} (API) to test

on:
  push:
    tags:
      - "*"

env:
  AWS_REGION: "ca-central-1"

defaults:
  run:
    working-directory: ./pdr-api

permissions:
  id-token: write
  contents: read

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    environment: test
    steps:
      ### Checkout GitHub Repo
      - name: Checkout repo
        uses:
          actions/checkout@v3
        with: 
          ref: ${{ github.ref_name }}

      ### Tag not found
      - name: Tag not found
        if: ${{ failure() }}
        run: |
          echo "::error::Git Tag not found, please double check input"
          exit 1

      ### Install if no cache exists
      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: |
            pdr-api/dependencies/nodejs/yarn.lock
          cache: "yarn"
      - run: |
          cd dependencies/nodejs
          yarn install --silent --frozen-lockfile

      ### Setup AWS SAM
      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      ### Assume AWS IAM Role
      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      ### Build inside Docker containers
      - name: SAM build
        run: |
          sam build --use-container
      ### Prevent prompts and failure when the stack is unchanged
      - name: SAM deploy
        env:
          STACK_NAME: ${{ vars.PDR_API_STACK_NAME }}
        run: |
          sam deploy --stack-name $STACK_NAME --no-confirm-changeset --no-fail-on-empty-changeset
