name: Deploy PDR-API Dev

on:
  push:
    branches: [main]
    paths: "pdr-api/**"
  workflow_dispatch:

env: 
  AWS_REGION: "ca-central-1"

permissions:
  id-token: write
  contents: read

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      # Build inside Docker containers
      - name: SAM build
        run: |
          cd pdr-api/ && sam build --use-container
      # Prevent prompts and failure when the stack is unchanged
      - name: SAM deploy
        run: |
          cd pdr-api/ && sam deploy --stack-name ${{ env.PDR_API_STACK_NAME}} --no-confirm-changeset --no-fail-on-empty-changeset
