name: Deploy PDR-Admin LZA Test

run-name: Deploying ${{ github.ref_name }} (Admin) to lza-test

on:
  release:
    types: [prereleased]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-admin:
    runs-on: ubuntu-latest
    environment: lza-test
    strategy:
      max-parallel: 1
      matrix:
        node-version: [20.x]
    defaults:
      run:
        working-directory: "./${{ vars.PDR_ADMIN_DIRECTORY }}"
    steps:
      ### Checkout GitHub Repo
      - name: Checkout repo
        uses: actions/checkout@v3

      ### Install if no cache exists ###
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: "${{ vars.PDR_ADMIN_DIRECTORY }}/yarn.lock"
      - run: yarn install --silent --frozen-lockfile

      ### Build if no cache exists ###
      - name: Cache Admin Build
        id: cache-admin-build
        uses: actions/cache@v3
        with:
          path: |
            **${{ vars.PDR_ADMIN_DIRECTORY }}/dist
          key: ${{ github.sha }}-${{ vars.PDR_ADMIN_DIRECTORY }}-dist
      - name: Run yarn build
        if: steps.cache-admin-build.outputs.cache-hit != 'true'
        env:
          GH_HASH: ${{ github.sha }}
        run: |
          sed 's@localConfigEndpoint@'true'@g' src/env.js.template | sed 's@localGHHash@'"$GH_HASH"'@g' > src/env.js
          yarn build

      ### Setup AWS SAM
      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      ### Assume AWS IAM Role
      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}

      ### SAM Build
      - name: Cache SAM Build
        id: cache-sam-build
        uses: actions/cache@v3
        with:
          path: |
            **${{ vars.PDR_ADMIN_DIRECTORY }}/.aws-sam
          key: ${{ github.sha }}-${{ vars.PDR_ADMIN_DIRECTORY }}-sam-cache
      - name: Run sam build
        if: steps.cache-sam-build.outputs.cache-hit != 'true'
        run: |
          sam build --cached

      ### Prevent prompts and failure when the stack is unchanged
      - name: SAM deploy
        env:
          PROJECT_NAME: ${{ vars.PDR_ADMIN_PROJECT_NAME || 'pdr-admin-lza-test' }}
          API_GATEWAY_ID: ${{ vars.PDR_API_ID }}
          ENV: ${{ vars.ENVIRONMENT_STAGE || 'lza-test' }}
          DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
          CREATE_CERTIFICATE: ${{ vars.CREATE_CERTIFICATE || 'false' }}
          EXISTING_CERTIFICATE_ARN: ${{ vars.EXISTING_CERTIFICATE_ARN || vars.AWS_CERTIFICATE_ARN || '' }}
          HOSTED_ZONE_ID: ${{ vars.HOSTED_ZONE_ID || '' }}
          BASE_HREF: "admin/"
        run: |
          sam deploy --config-env lza-test --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides \
          "ProjectName=$PROJECT_NAME \
          DistOriginPath=latest \
          ApiGatewayId=$API_GATEWAY_ID \
          Env=$ENV \
          AWSRegion=ca-central-1 \
          ApiStage=api \
          EnvDomainName=$DOMAIN_NAME \
          CreateCertificate=$CREATE_CERTIFICATE \
          ExistingCertificateArn=$EXISTING_CERTIFICATE_ARN \
          HostedZoneId=$HOSTED_ZONE_ID \
          BaseHref=$BASE_HREF"

      ### Upload dist to S3 ###
      - name: Deploy to S3
        env:
          S3_BUCKET: ${{ vars.PDR_ADMIN_PROJECT_NAME }}-${{ vars.ENVIRONMENT_STAGE }}
          DIR_NAME: ${{ github.sha }}
          WORKING_DIRECTORY: ${{ vars.PDR_ADMIN_DIRECTORY }}
        run: |
          aws s3 sync dist/$WORKING_DIRECTORY s3://$S3_BUCKET/$DIR_NAME
          aws s3 rm s3://$S3_BUCKET/ --recursive --exclude "*" --include "latest/admin/*"
          aws s3 sync dist/$WORKING_DIRECTORY s3://$S3_BUCKET/latest/admin

      - name: Invalidate CloudFront
        continue-on-error: true
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: "/*"

