name: PR Checks
run-name: Run test-ci on PR ${{ github.event.number }} (Admin)

on:
  pull_request:
    paths: ["pdr-admin/**"]

jobs:
  test-ci:
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [20.x]
    defaults:
      run:
        working-directory: "./pdr-admin"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      ### Install if no cache exists ###
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: "pdr-admin/yarn.lock"
      - run: yarn install --silent --frozen-lockfile
      - run: yarn test:cov
      - uses: actions/upload-artifact@master
        with:
          name: coverage
          path: pdr-admin/coverage/

  sonar-cloud:
    needs: test-ci
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/download-artifact@master
        with:
          name: coverage
          path: pdr-admin/coverage/
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: pdr-admin/
          args: >
            -Dsonar.organization=bcgov-sonarcloud
            -Dsonar.projectKey=bcgov_parks-data-register
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.sources=src
            -Dsonar.inclusions=**/*.ts
            -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts
            -Dsonar.tests=src
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.typescript.tsconfigPath=pdr-admin/tsconfig.jsom
            -Dsonar.javascript.lcov.reportPaths=coverage/pdr-admin/lcov.info
            -Dsonar.qualitygate.wait=true