name: PR Checks (API)
run-name: Run test on PR ${{ github.event.number }} (API)

on:
  pull_request:
    paths: "pdr-api/**"

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [18.x]
    defaults:
      run:
        working-directory: "./pdr-api"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      ### Install if no cache exists ###
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: "pdr-api/yarn.lock"
      - run: yarn install --silent --frozen-lockfile

      ### Setup AWS SAM 
      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-intaller: true

      ### SAM Build
      - name: Cache SAM Build
        id: cache-sam-build
        uses: actions/cache@v3
        with:
          path: |
            pdr-api/.aws-sam
          key: ${{ github.sha }}-pdr-api-sam-cache
      - name: Run sam build
        if: steps.cache-sam-build.outputs.cache-hit != 'true'
        run: |
          sam build --cached --parallel
    
      ### Set up DynamoDB local
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v3.0.0
        with:
          sharedDb: true
          port: 8000
          cors: '*'

      ### Run Tests
      - name: Run Tests  
        env:
          TABLE_NAME: NameRegister-tests
          IS_OFFLINE: true
          DYNAMODB_ENDPOINT_URL: http://127.0.0.1:8000
          AWS_REGION: local-env
          AWS_ACCESS_KEY_ID: notused
          AWS_SECRET_ACCESS_KEY: notused
        run: jest --coverage
