name: PR Checks
run-name: Run test-ci on PR ${{ github.ref }} (Admin)

on:
  pull_request:
    paths: "pdr-admin/**"

jobs:
  test:
    name: "Run Admin Test-ci on PR"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    defaults:
      run:
        working-directory: "./${{ vars.PDR_ADMIN_DIRECTORY }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      ### Install if no cache exists ###
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: "${{ vars.PDR_ADMIN_DIRECTORY }}/yarn.lock"
      - run: yarn install --silent --frozen-lockfile
      - run: yarn test-ci
