name: PR Checks
run-name: Run test-ci on PR ${{ github.event.number }} (Admin)

on:
  pull_request:
    paths: "pdr-admin/**"

jobs:
  test-ci:
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [18.x]
    defaults:
      run:
        working-directory: "./pdr-admin"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      ### Install if no cache exists ###
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: "pdr-admin/yarn.lock"
      - name: Test and Analyse
        uses: bcgov-nr/action-test-and-analyse@v1.2.1
        with:
          commands: |
            yarn install --silent --frozen-lockfile
            yarn test-cov
          dir: ./
          node_version: "20"
          sonar_args: >
            -Dsonar.exclusions=**/coverage/**,**/node_modules/**,**/*spec.ts
            -Dsonar.organization=bcgov-sonarcloud
            -Dsonar.projectKey=bcgov_parks-data-register
            -Dsonar.sources=src
            -Dsonar.tests.inclusions=**/*spec.ts
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
          sonar_token: ${{ secrets.SONAR_TOKEN }}
