name: SonarCloud Scan
run-name: SonarCloud Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-admin:
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [20.x]
    defaults:
      run:
        working-directory: "./pdr-admin"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      ### Install if no cache exists ###
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: "pdr-admin/yarn.lock"
      - run: yarn install --silent --frozen-lockfile
      - run: yarn test:cov
      - uses: actions/upload-artifact@master
        with:
          name: coverage-admin
          path: pdr-admin/coverage/

  test-api:
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [18.x]
    defaults:
      run:
        working-directory: "./pdr-api"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      ### Install if no cache exists ###
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: "pdr-api/yarn.lock"
      - run: yarn install --silent --frozen-lockfile

      ### Setup AWS SAM
      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      ### SAM Build
      - name: Cache SAM Build
        id: cache-sam-build
        uses: actions/cache@v3
        with:
          path: |
            pdr-api/.aws-sam
          key: ${{ github.sha }}-pdr-api-sam-cache
      - name: Run sam build
        if: steps.cache-sam-build.outputs.cache-hit != 'true'
        run: |
          sam build --cached --parallel

      ### Set up DynamoDB local
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v3.0.0
        with:
          sharedDb: true
          port: 8000
          cors: '*'

      - name: Sleep so DynamoDB has time to wake up
        uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: '15' # for 15 seconds

      ### Run Tests
      - name: Run Tests
        env:
          TABLE_NAME: NameRegister-tests
          IS_OFFLINE: true
          DYNAMODB_ENDPOINT_URL: http://127.0.0.1:8000
          AWS_REGION: local-env
          AWS_ACCESS_KEY_ID: notused
          AWS_SECRET_ACCESS_KEY: notused
        run: ./node_modules/jest/bin/jest.js --coverage --runInBand
      - uses: actions/upload-artifact@master
        with:
          name: coverage-api
          path: pdr-api/coverage/

  sonar-cloud-admin:
    needs: test-admin
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/download-artifact@master
        with:
          name: coverage-admin
          path: pdr-admin/coverage/
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: pdr-admin/
          args: >
            -Dsonar.organization=bcgov-sonarcloud
            -Dsonar.projectKey=bcgov_parks-data-register
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.sources=src
            -Dsonar.inclusions=**/*.ts
            -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts
            -Dsonar.tests=src
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.typescript.tsconfigPath=pdr-admin/tsconfig.jsom
            -Dsonar.javascript.lcov.reportPaths=coverage/pdr-admin/lcov.info
            -Dsonar.qualitygate.wait=true

  sonar-cloud-api:
    needs: test-api
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/download-artifact@master
        with:
          name: coverage-api
          path: pdr-api/coverage/
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: pdr-api/
          args: >
            -Dsonar.organization=bcgov-sonarcloud
            -Dsonar.projectKey=bcgov_parks-data-register
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.sources=handlers
            -Dsonar.inclusions=**/*.js
            -Dsonar.exclusions=**/node_modules/**,**/*.test.ts
            -Dsonar.tests=handlers
            -Dsonar.test.inclusions=**/*.test.ts
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.qualitygate.wait=true