name: Sonar Cloud Analysis
on:
  push:
      branches:
      - main
  workflow_dispatch:
jobs:
  sonarcloudScanAdmin:
    name: sonarcloudScanAdmin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: pdr-admin/
          args: >
            -Dsonar.organization=bcgov-sonarcloud
            -Dsonar.projectKey=bcgov_parks-data-register
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.sources=src
            -Dsonar.inclusions=**/*.ts,**/*.scss,**/*.html
            -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts
            -Dsonar.javascript.lcov.reportPaths=pdr-admin/coverage/pdr-admin/lcov.info

  sonarcloudScanApi:
    name: sonarcloudScanApi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: pdr-api/
          args: >
            -Dsonar.organization=bcgov-sonarcloud
            -Dsonar.projectKey=bcgov_parks-data-register
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.inclusions=**/*.js
            -Dsonar.exclusions=**/node_modules/**,**/__tests__/*.ts